stateDiagram-v2
	%% variableName: Display Name
	Login: Login
	AuthCheck: Check Authorization
	LoadSystem: Load System
	Dashboard: Show Dashboard
	ShowMenu: ShowMenu
	LoadProfile: Load Profile Data
	CheckNotifications: Check Notifications
	SystemReady: System is Ready
	LogOut: Log Out

	%% syntax for split/merge nodes
	%% state variableName <<choice>>
	state authSplit <<choice>>
	state userSplit <<choice>>

	%% syntax for fork/join nodes
	%% state variableName <<fork/join>>
	state systemFork <<fork>>
	state systemJoin <<join>>

	[*]-->Login
	Login-->AuthCheck
	AuthCheck-->authSplit
	authSplit-->Login: Invalid Credentials
	authSplit-->LoadSystem: Valid Credentials
	LoadSystem --> systemFork
	systemFork-->LoadProfile
	LoadProfile-->systemJoin
	systemFork-->CheckNotifications
	CheckNotifications-->systemJoin
	systemJoin-->SystemReady
	SystemReady-->Dashboard
	Dashboard-->ShowMenu
	ShowMenu-->userSplit
	userSplit-->LoadSystem: User refreshes system
	userSplit-->LogOut: User selects Log Out
	LogOut-->[*]